-- The whole database: the scraper's tables, and the category tree the webapp reads.
--
-- Postgres runs this file by itself on the first start of an empty data volume.
-- Every statement is safe to repeat, so after editing the categories, apply it to
-- the running database without losing products or prices:
--
--   docker exec -i market_postgres sh -c 'psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -v ON_ERROR_STOP=1' < db/init.sql
--
-- Only the category tables are rebuilt; markets, products and prices are kept.

CREATE TABLE IF NOT EXISTS markets (
    id    SERIAL PRIMARY KEY,
    name  TEXT UNIQUE NOT NULL
);

INSERT INTO markets (name) VALUES
    ('a101'), ('carrefour'), ('getir'), ('migros'), ('sok')
ON CONFLICT (name) DO NOTHING;

-- One row per product per market: details that rarely change
CREATE TABLE IF NOT EXISTS products (
    id           SERIAL PRIMARY KEY,
    market_id    INT  NOT NULL REFERENCES markets(id),
    external_id  TEXT NOT NULL,          -- the market's own product id
    name         TEXT NOT NULL,
    brand        TEXT,
    barcode      TEXT,                   -- EAN, for cross-market matching
    category     TEXT,                   -- the market's own category name
    quantity     NUMERIC(10,3),          -- e.g. 500
    unit         TEXT,                   -- 'g', 'kg', 'ml', 'l', 'adet'
    url          TEXT,
    image_url    TEXT,
    UNIQUE (market_id, external_id)
);

CREATE INDEX IF NOT EXISTS idx_products_barcode ON products (barcode);

-- One row per product per store per day: the price history
CREATE TABLE IF NOT EXISTS prices (
    id             BIGSERIAL PRIMARY KEY,
    product_id     INT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    price          NUMERIC(10,2) NOT NULL,   -- what the customer pays
    regular_price  NUMERIC(10,2),            -- price before discount
    discount_rate  SMALLINT,                 -- e.g. 33 for %33
    in_stock       BOOLEAN NOT NULL DEFAULT TRUE,
    store_code     TEXT NOT NULL DEFAULT '', -- '' when the market has one price
    scraped_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- At most one price per product per store per (Istanbul) day, so a rerun
-- on the same day updates the row instead of adding a duplicate
CREATE UNIQUE INDEX IF NOT EXISTS uq_prices_daily ON prices (
    product_id, store_code, ((scraped_at AT TIME ZONE 'Europe/Istanbul')::date)
);

CREATE INDEX IF NOT EXISTS idx_prices_scraped_at ON prices (scraped_at);

-- Categories -----------------------------------------------------------------
-- Our own category tree, shared by all markets, and rules mapping each market's
-- categories onto it. Only the webapp reads these; the scraper keeps writing
-- products.category as the market names it.

-- main > sub, e.g. 'Süt & Kahvaltılık' > 'Peynir'. A subcategory exists only when every
-- market that sells those products keeps them apart; otherwise a market lumping them
-- together would be missing from it, and the comparison would be unfair.
CREATE TABLE IF NOT EXISTS categories (
    id         SERIAL PRIMARY KEY,
    parent_id  INT REFERENCES categories(id) ON DELETE CASCADE,  -- NULL for a main category
    name       TEXT NOT NULL,
    slug       TEXT UNIQUE NOT NULL,   -- the path, e.g. 'sut-kahvaltilik/peynir'
    position   INT  NOT NULL DEFAULT 0 -- display order among siblings
);

CREATE INDEX IF NOT EXISTS idx_categories_parent ON categories (parent_id);

-- A rule: products whose category is market_category, or anything below it
-- (market_category || ' > ...'), belong to category_id. The longest matching
-- rule wins, so 'İçecekler > Gazsız İçecekler > Ayran' can override 'İçecekler > Gazsız İçecekler'.
CREATE TABLE IF NOT EXISTS category_map (
    market_id        INT  NOT NULL REFERENCES markets(id),
    market_category  TEXT NOT NULL,
    category_id      INT  NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    PRIMARY KEY (market_id, market_category)
);

-- The view below reads the distinct (market, category) pairs of products
CREATE INDEX IF NOT EXISTS idx_products_market_category ON products (market_id, category);

-- Every market category that occurs in products, with the category it resolves to.
-- There are only a few thousand distinct market categories, so the prefix matching
-- runs over those instead of over every product. Categories no rule matches are absent.
CREATE OR REPLACE VIEW category_resolution AS
SELECT DISTINCT ON (c.market_id, c.category)
    c.market_id, c.category, m.category_id
FROM (SELECT DISTINCT market_id, category FROM products) c
JOIN category_map m
  ON m.market_id = c.market_id
 AND (c.category = m.market_category OR starts_with(c.category, m.market_category || ' > '))
ORDER BY c.market_id, c.category, length(m.market_category) DESC;

-- The tree and the rules, rebuilt from scratch in one transaction --------------

BEGIN;

DELETE FROM category_map;
DELETE FROM categories;

-- The tree, in display order. A slug is the category's path; its parent is the
-- slug without the last segment.
CREATE TEMP TABLE tree (slug TEXT PRIMARY KEY, name TEXT NOT NULL, position SERIAL) ON COMMIT DROP;
INSERT INTO tree (slug, name) VALUES
    ('meyve-sebze', 'Meyve & Sebze'),
    ('meyve-sebze/meyve', 'Meyve'),
    ('meyve-sebze/sebze', 'Sebze'),
    ('meyve-sebze/yesillik', 'Yeşillik'),

    ('et-tavuk-balik', 'Et, Tavuk & Balık'),
    ('et-tavuk-balik/kirmizi-et', 'Kırmızı Et'),
    ('et-tavuk-balik/beyaz-et', 'Beyaz Et'),
    ('et-tavuk-balik/balik', 'Balık & Deniz Ürünleri'),
    ('et-tavuk-balik/sarkuteri', 'Şarküteri'),

    ('sut-kahvaltilik', 'Süt & Kahvaltılık'),
    ('sut-kahvaltilik/sut', 'Süt'),
    ('sut-kahvaltilik/yogurt', 'Yoğurt'),
    ('sut-kahvaltilik/ayran-kefir', 'Ayran & Kefir'),
    ('sut-kahvaltilik/peynir', 'Peynir'),
    ('sut-kahvaltilik/tereyagi-margarin', 'Tereyağı & Margarin'),
    ('sut-kahvaltilik/kaymak-krema', 'Kaymak & Krema'),
    ('sut-kahvaltilik/yumurta', 'Yumurta'),
    ('sut-kahvaltilik/zeytin', 'Zeytin'),
    ('sut-kahvaltilik/bal-recel', 'Bal & Reçel'),
    ('sut-kahvaltilik/helva-tahin', 'Helva, Tahin & Pekmez'),
    ('sut-kahvaltilik/ezmeler', 'Krem Çikolata & Ezmeler'),
    ('sut-kahvaltilik/gevrek', 'Kahvaltılık Gevrek'),
    ('sut-kahvaltilik/sutlu-tatli', 'Sütlü Tatlı & Puding'),

    ('temel-gida', 'Temel Gıda'),
    ('temel-gida/bakliyat', 'Bakliyat, Pirinç & Bulgur'),
    ('temel-gida/makarna', 'Makarna & Erişte'),
    ('temel-gida/un', 'Un & İrmik'),
    ('temel-gida/seker', 'Şeker & Tatlandırıcı'),
    ('temel-gida/sivi-yag', 'Sıvı Yağ'),
    ('temel-gida/salca', 'Salça'),
    ('temel-gida/sos', 'Sos & Sirke'),
    ('temel-gida/baharat', 'Tuz, Baharat & Bulyon'),
    ('temel-gida/konserve', 'Konserve & Turşu'),
    ('temel-gida/pasta-malzemeleri', 'Pasta Malzemeleri'),
    ('temel-gida/corba', 'Çorba'),

    ('firin', 'Fırın & Pastane'),
    ('firin/ekmek', 'Ekmek'),
    ('firin/unlu-mamuller', 'Unlu Mamuller & Kurabiye'),
    ('firin/tatli-pasta', 'Tatlı & Pasta'),

    ('atistirmalik', 'Atıştırmalık'),
    ('atistirmalik/cikolata', 'Çikolata'),
    ('atistirmalik/biskuvi-kraker', 'Bisküvi & Kraker'),
    ('atistirmalik/kek', 'Kek'),
    ('atistirmalik/gofret-bar', 'Gofret & Bar'),
    ('atistirmalik/cips', 'Cips & Patlamış Mısır'),
    ('atistirmalik/kuruyemis', 'Kuruyemiş & Kuru Meyve'),
    ('atistirmalik/sekerleme-sakiz', 'Şekerleme & Sakız'),
    ('atistirmalik/dondurma', 'Dondurma'),

    ('icecek', 'İçecek'),
    ('icecek/su', 'Su'),
    ('icecek/maden-suyu', 'Maden Suyu'),
    ('icecek/gazli', 'Gazlı İçecek'),
    ('icecek/gazsiz', 'Meyve Suyu & Gazsız İçecekler'),
    ('icecek/enerji', 'Enerji & Spor İçecekleri'),
    ('icecek/cay', 'Çay'),
    ('icecek/kahve', 'Kahve'),

    ('dondurulmus-hazir', 'Dondurulmuş & Hazır Yemek'),
    ('dondurulmus-hazir/dondurulmus', 'Dondurulmuş Gıda'),
    ('dondurulmus-hazir/hazir-yemek', 'Hazır Yemek & Meze'),

    ('temizlik', 'Temizlik'),
    ('temizlik/camasir', 'Çamaşır'),
    ('temizlik/bulasik', 'Bulaşık'),
    ('temizlik/genel', 'Genel Temizlik'),
    ('temizlik/oda-kokusu', 'Oda Kokusu'),
    ('temizlik/hasere', 'Haşere'),
    ('temizlik/malzemeler', 'Temizlik Malzemeleri & Çöp Torbası'),

    ('kagit', 'Kağıt Ürünleri'),
    ('kagit/tuvalet-kagidi', 'Tuvalet Kağıdı'),
    ('kagit/kagit-havlu', 'Kağıt Havlu'),
    ('kagit/pecete-mendil', 'Peçete & Mendil'),
    ('kagit/islak-mendil', 'Islak Mendil'),

    ('kisisel-bakim', 'Kişisel Bakım'),
    ('kisisel-bakim/sac', 'Saç Bakım & Boya'),
    ('kisisel-bakim/agiz-dis', 'Ağız & Diş'),
    ('kisisel-bakim/dus-banyo', 'Duş, Banyo & Sabun'),
    ('kisisel-bakim/cilt', 'Cilt & Güneş Bakımı'),
    ('kisisel-bakim/deodorant-parfum', 'Deodorant & Parfüm'),
    ('kisisel-bakim/kolonya', 'Kolonya'),
    ('kisisel-bakim/tiras', 'Tıraş'),
    ('kisisel-bakim/agda', 'Ağda & Epilasyon'),
    ('kisisel-bakim/ped', 'Hijyenik Ped'),
    ('kisisel-bakim/makyaj', 'Makyaj'),
    ('kisisel-bakim/saglik', 'Sağlık Ürünleri'),

    ('anne-bebek', 'Anne & Bebek'),
    ('anne-bebek/bebek-bezi', 'Bebek Bezi'),
    ('anne-bebek/mama', 'Mama & Beslenme'),
    ('anne-bebek/bakim', 'Bebek Bakım'),
    ('anne-bebek/gerecler', 'Bebek Gereçleri'),

    ('evcil-hayvan', 'Evcil Hayvan'),
    ('evcil-hayvan/kedi', 'Kedi'),
    ('evcil-hayvan/kopek', 'Köpek'),
    ('evcil-hayvan/diger', 'Diğer Evcil Hayvanlar'),

    ('saglikli-yasam', 'Sağlıklı Yaşam'),
    ('saglikli-yasam/organik-glutensiz', 'Organik & Glutensiz'),
    ('saglikli-yasam/vegan', 'Vegan & Bitkisel'),
    ('saglikli-yasam/takviye', 'Takviye & Sporcu'),

    ('diger', 'Diğer'),
    ('diger/giyim', 'Giyim & Ayakkabı'),
    ('diger/elektronik', 'Elektronik'),
    ('diger/ev-mutfak', 'Ev & Mutfak'),
    ('diger/bahce-spor', 'Bahçe, Kamp & Spor'),
    ('diger/hirdavat-oto', 'Hırdavat & Oto'),
    ('diger/kitap-kirtasiye', 'Kitap & Kırtasiye'),
    ('diger/oyuncak', 'Oyuncak'),
    ('diger/hediye', 'Parti, Çiçek & Hediye');

-- Parents before children: main categories, then subcategories
INSERT INTO categories (name, slug, position)
SELECT name, slug, position FROM tree WHERE slug NOT LIKE '%/%';

INSERT INTO categories (parent_id, name, slug, position)
SELECT p.id, t.name, t.slug, t.position
FROM tree t JOIN categories p ON p.slug = split_part(t.slug, '/', 1)
WHERE t.slug LIKE '%/%';

-- Rules: (market, market category prefix, our category slug). A rule covers the
-- market category and everything below it; the longest matching rule wins. Each
-- market's top-level categories have a rule, so a category a market adds later
-- still lands under the right main category.
CREATE TEMP TABLE rules (market TEXT, market_category TEXT, slug TEXT) ON COMMIT DROP;
INSERT INTO rules VALUES
    -- a101 -----------------------------------------------------------------------
    ('a101', 'Anne Bebek', 'anne-bebek'),
    ('a101', 'Anne Bebek > Bebek Banyo', 'anne-bebek/bakim'),
    ('a101', 'Anne Bebek > Bebek Beslenme', 'anne-bebek/mama'),
    ('a101', 'Anne Bebek > Bebek Bezi', 'anne-bebek/bebek-bezi'),
    ('a101', 'Anne Bebek > Islak Havlu', 'anne-bebek/bakim'),
    ('a101', 'Atıştırmalık', 'atistirmalik'),
    ('a101', 'Atıştırmalık > Bisküvi, Kraker', 'atistirmalik/biskuvi-kraker'),
    ('a101', 'Atıştırmalık > Cips', 'atistirmalik/cips'),
    ('a101', 'Atıştırmalık > Gofret', 'atistirmalik/gofret-bar'),
    ('a101', 'Atıştırmalık > Kek', 'atistirmalik/kek'),
    ('a101', 'Atıştırmalık > Kuruyemiş, Kuru Meyve', 'atistirmalik/kuruyemis'),
    ('a101', 'Atıştırmalık > Sakız, Şekerleme', 'atistirmalik/sekerleme-sakiz'),
    ('a101', 'Atıştırmalık > Sağlıklı Atıştırmalıklar', 'atistirmalik/gofret-bar'),
    ('a101', 'Atıştırmalık > Çikolata', 'atistirmalik/cikolata'),
    ('a101', 'Dondurma', 'atistirmalik/dondurma'),
    ('a101', 'Donuk, Hazır Yemek, Meze', 'dondurulmus-hazir'),
    ('a101', 'Donuk, Hazır Yemek, Meze > Dondurulmuş Gıda', 'dondurulmus-hazir/dondurulmus'),
    ('a101', 'Donuk, Hazır Yemek, Meze > Dondurulmuş Tatlı', 'dondurulmus-hazir/dondurulmus'),
    ('a101', 'Donuk, Hazır Yemek, Meze > Hazır Tatlılar', 'firin/tatli-pasta'),
    ('a101', 'Donuk, Hazır Yemek, Meze > Kuru Tatlılar', 'firin/tatli-pasta'),
    ('a101', 'Donuk, Hazır Yemek, Meze > Meze', 'dondurulmus-hazir/hazir-yemek'),
    ('a101', 'Donuk, Hazır Yemek, Meze > Pratik Yemekler', 'dondurulmus-hazir/hazir-yemek'),
    ('a101', 'Donuk, Hazır Yemek, Meze > Sandviç, Dürümler', 'dondurulmus-hazir/hazir-yemek'),
    ('a101', 'Elektronik', 'diger/elektronik'),
    ('a101', 'Et, Tavuk, Şarküteri', 'et-tavuk-balik'),
    ('a101', 'Et, Tavuk, Şarküteri > Beyaz Et', 'et-tavuk-balik/beyaz-et'),
    ('a101', 'Et, Tavuk, Şarküteri > Deniz Ürünleri', 'et-tavuk-balik/balik'),
    ('a101', 'Et, Tavuk, Şarküteri > Kırmızı Et', 'et-tavuk-balik/kirmizi-et'),
    ('a101', 'Et, Tavuk, Şarküteri > Şarküteri', 'et-tavuk-balik/sarkuteri'),
    ('a101', 'Ev Yaşam', 'diger/ev-mutfak'),
    ('a101', 'Ev Yaşam > Bahçe Malzemeleri', 'diger/bahce-spor'),
    ('a101', 'Ev Yaşam > Giyim, Aksesuar', 'diger/giyim'),
    ('a101', 'Ev Yaşam > Kitap, Kırtasiye', 'diger/kitap-kirtasiye'),
    ('a101', 'Ev Yaşam > Nalburiye, Hırdavat', 'diger/hirdavat-oto'),
    ('a101', 'Ev Yaşam > Oto Ürünleri, Aksesuarları', 'diger/hirdavat-oto'),
    ('a101', 'Ev Yaşam > Oyuncak', 'diger/oyuncak'),
    ('a101', 'Ev Yaşam > Seyahat Ürünleri', 'diger/bahce-spor'),
    ('a101', 'Ev Yaşam > Spor Hobi Ürünleri', 'diger/bahce-spor'),
    ('a101', 'Evcil Hayvan', 'evcil-hayvan'),
    ('a101', 'Evcil Hayvan > Kedi', 'evcil-hayvan/kedi'),
    ('a101', 'Evcil Hayvan > Köpek', 'evcil-hayvan/kopek'),
    ('a101', 'Fırından', 'firin'),
    ('a101', 'Fırından > Ekmek', 'firin/ekmek'),
    ('a101', 'Fırından > Hamur Pasta Malzemeleri', 'temel-gida/pasta-malzemeleri'),
    ('a101', 'Fırından > Unlu Mamüller', 'firin/unlu-mamuller'),
    ('a101', 'Kağıt Ürünleri', 'kagit'),
    ('a101', 'Kağıt Ürünleri > Islak Mendil', 'kagit/islak-mendil'),
    ('a101', 'Kağıt Ürünleri > Kağıt Havlu', 'kagit/kagit-havlu'),
    ('a101', 'Kağıt Ürünleri > Kağıt Peçete, Mendil', 'kagit/pecete-mendil'),
    ('a101', 'Kağıt Ürünleri > Tuvalet Kağıdı', 'kagit/tuvalet-kagidi'),
    ('a101', 'Kişisel Bakım', 'kisisel-bakim'),
    ('a101', 'Kişisel Bakım > Ağda Epilasyon', 'kisisel-bakim/agda'),
    ('a101', 'Kişisel Bakım > Ağız Bakım Ürünleri', 'kisisel-bakim/agiz-dis'),
    ('a101', 'Kişisel Bakım > Cilt Bakımı', 'kisisel-bakim/cilt'),
    ('a101', 'Kişisel Bakım > Duş, Banyo, Sabun', 'kisisel-bakim/dus-banyo'),
    ('a101', 'Kişisel Bakım > Erkek Bakım', 'kisisel-bakim/tiras'),
    ('a101', 'Kişisel Bakım > Güneş Bakım', 'kisisel-bakim/cilt'),
    ('a101', 'Kişisel Bakım > Hijyenik Ped', 'kisisel-bakim/ped'),
    ('a101', 'Kişisel Bakım > Kolonya', 'kisisel-bakim/kolonya'),
    ('a101', 'Kişisel Bakım > Makyaj', 'kisisel-bakim/makyaj'),
    ('a101', 'Kişisel Bakım > Parfüm, Deodorant', 'kisisel-bakim/deodorant-parfum'),
    ('a101', 'Kişisel Bakım > Saç Bakım', 'kisisel-bakim/sac'),
    ('a101', 'Kişisel Bakım > Sağlık Ürünleri', 'kisisel-bakim/saglik'),
    ('a101', 'Meyve, Sebze', 'meyve-sebze'),
    ('a101', 'Meyve, Sebze > Meyve', 'meyve-sebze/meyve'),
    ('a101', 'Meyve, Sebze > Sebze', 'meyve-sebze/sebze'),
    ('a101', 'Meyve, Sebze > Yeşillik', 'meyve-sebze/yesillik'),
    ('a101', 'Su, İçecek', 'icecek'),
    ('a101', 'Su, İçecek > Ayran, Kefir', 'sut-kahvaltilik/ayran-kefir'),
    ('a101', 'Su, İçecek > Bitki Çayları', 'icecek/cay'),
    ('a101', 'Su, İçecek > Enerji İçeceği', 'icecek/enerji'),
    ('a101', 'Su, İçecek > Gazlı İçecekler', 'icecek/gazli'),
    ('a101', 'Su, İçecek > Gazsız İçecekler', 'icecek/gazsiz'),
    ('a101', 'Su, İçecek > Kahve', 'icecek/kahve'),
    ('a101', 'Su, İçecek > Maden Suyu', 'icecek/maden-suyu'),
    ('a101', 'Su, İçecek > Su', 'icecek/su'),
    ('a101', 'Su, İçecek > Çay', 'icecek/cay'),
    ('a101', 'Süt Ürünleri, Kahvaltılık', 'sut-kahvaltilik'),
    ('a101', 'Süt Ürünleri, Kahvaltılık > Bal, Reçel', 'sut-kahvaltilik/bal-recel'),
    ('a101', 'Süt Ürünleri, Kahvaltılık > Beyaz Peynir', 'sut-kahvaltilik/peynir'),
    ('a101', 'Süt Ürünleri, Kahvaltılık > Helva, Tahin, Pekmez', 'sut-kahvaltilik/helva-tahin'),
    ('a101', 'Süt Ürünleri, Kahvaltılık > Kahvaltılık Gevrek', 'sut-kahvaltilik/gevrek'),
    ('a101', 'Süt Ürünleri, Kahvaltılık > Kaymak, Krema', 'sut-kahvaltilik/kaymak-krema'),
    ('a101', 'Süt Ürünleri, Kahvaltılık > Kaşar Peyniri', 'sut-kahvaltilik/peynir'),
    ('a101', 'Süt Ürünleri, Kahvaltılık > Sürülebilir Peynir', 'sut-kahvaltilik/peynir'),
    ('a101', 'Süt Ürünleri, Kahvaltılık > Sürülebilir Ürünler', 'sut-kahvaltilik/ezmeler'),
    ('a101', 'Süt Ürünleri, Kahvaltılık > Süt', 'sut-kahvaltilik/sut'),
    ('a101', 'Süt Ürünleri, Kahvaltılık > Tereyağ, Margarin', 'sut-kahvaltilik/tereyagi-margarin'),
    ('a101', 'Süt Ürünleri, Kahvaltılık > Yoğurt', 'sut-kahvaltilik/yogurt'),
    ('a101', 'Süt Ürünleri, Kahvaltılık > Yumurta', 'sut-kahvaltilik/yumurta'),
    ('a101', 'Süt Ürünleri, Kahvaltılık > Yöresel Peynir', 'sut-kahvaltilik/peynir'),
    ('a101', 'Süt Ürünleri, Kahvaltılık > Zeytin', 'sut-kahvaltilik/zeytin'),
    ('a101', 'Temel Gıda', 'temel-gida'),
    ('a101', 'Temel Gıda > Bakliyat', 'temel-gida/bakliyat'),
    ('a101', 'Temel Gıda > Bulyonlar', 'temel-gida/baharat'),
    ('a101', 'Temel Gıda > Erişte, Mantı', 'temel-gida/makarna'),
    ('a101', 'Temel Gıda > Hazır Çorbalar', 'temel-gida/corba'),
    ('a101', 'Temel Gıda > Ketçap, Mayonez, Soslar, Sirkeler', 'temel-gida/sos'),
    ('a101', 'Temel Gıda > Konserve', 'temel-gida/konserve'),
    ('a101', 'Temel Gıda > Makarna, Noodle', 'temel-gida/makarna'),
    ('a101', 'Temel Gıda > Salça', 'temel-gida/salca'),
    ('a101', 'Temel Gıda > Sıvı Yağlar', 'temel-gida/sivi-yag'),
    ('a101', 'Temel Gıda > Turşu', 'temel-gida/konserve'),
    ('a101', 'Temel Gıda > Tuz, Baharat, Harç', 'temel-gida/baharat'),
    ('a101', 'Temel Gıda > Un', 'temel-gida/un'),
    ('a101', 'Temel Gıda > Şeker', 'temel-gida/seker'),
    ('a101', 'Temizlik Ürünleri', 'temizlik'),
    ('a101', 'Temizlik Ürünleri > Bulaşık', 'temizlik/bulasik'),
    ('a101', 'Temizlik Ürünleri > Genel Temizlik', 'temizlik/genel'),
    ('a101', 'Temizlik Ürünleri > Haşere Öldürücüler', 'temizlik/hasere'),
    ('a101', 'Temizlik Ürünleri > Oda Kokuları', 'temizlik/oda-kokusu'),
    ('a101', 'Temizlik Ürünleri > Temizlik Malzemeleri', 'temizlik/malzemeler'),
    ('a101', 'Temizlik Ürünleri > Çamaşır', 'temizlik/camasir'),

    -- carrefour ------------------------------------------------------------------
    ('carrefour', 'Atıştırmalık', 'atistirmalik'),
    ('carrefour', 'Atıştırmalık > Bar ve Gofret', 'atistirmalik/gofret-bar'),
    ('carrefour', 'Atıştırmalık > Bisküvi', 'atistirmalik/biskuvi-kraker'),
    ('carrefour', 'Atıştırmalık > Cipsler', 'atistirmalik/cips'),
    ('carrefour', 'Atıştırmalık > Kek ve Kruvasan', 'atistirmalik/kek'),
    ('carrefour', 'Atıştırmalık > Kuru Meyve', 'atistirmalik/kuruyemis'),
    ('carrefour', 'Atıştırmalık > Kuruyemiş', 'atistirmalik/kuruyemis'),
    ('carrefour', 'Atıştırmalık > Sakızlar', 'atistirmalik/sekerleme-sakiz'),
    ('carrefour', 'Atıştırmalık > Çikolata', 'atistirmalik/cikolata'),
    ('carrefour', 'Atıştırmalık > Şekerleme', 'atistirmalik/sekerleme-sakiz'),
    ('carrefour', 'Bebek Ürünleri', 'anne-bebek'),
    ('carrefour', 'Bebek Ürünleri > Bebek Araç Gereçleri', 'anne-bebek/gerecler'),
    ('carrefour', 'Bebek Ürünleri > Bebek Bakım', 'anne-bebek/bakim'),
    ('carrefour', 'Bebek Ürünleri > Bebek Beslenme', 'anne-bebek/mama'),
    ('carrefour', 'Bebek Ürünleri > Bebek Bezi', 'anne-bebek/bebek-bezi'),
    ('carrefour', 'Bebek Ürünleri > Bebek Hijyen', 'anne-bebek/bakim'),
    ('carrefour', 'Dondurma', 'atistirmalik/dondurma'),
    ('carrefour', 'Elektronik', 'diger/elektronik'),
    ('carrefour', 'Et, Tavuk, Balık', 'et-tavuk-balik'),
    ('carrefour', 'Et, Tavuk, Balık > Balık ve Deniz Mahsülleri', 'et-tavuk-balik/balik'),
    ('carrefour', 'Et, Tavuk, Balık > Beyaz Et', 'et-tavuk-balik/beyaz-et'),
    ('carrefour', 'Et, Tavuk, Balık > Hindi', 'et-tavuk-balik/beyaz-et'),
    ('carrefour', 'Et, Tavuk, Balık > Piliç', 'et-tavuk-balik/beyaz-et'),
    ('carrefour', 'Et, Tavuk, Balık > Kırmızı Et', 'et-tavuk-balik/kirmizi-et'),
    ('carrefour', 'Et, Tavuk, Balık > Şarküteri', 'et-tavuk-balik/sarkuteri'),
    ('carrefour', 'Ev, Yaşam', 'diger/ev-mutfak'),
    ('carrefour', 'Ev, Yaşam > Ayakkabı ve Terlik', 'diger/giyim'),
    ('carrefour', 'Ev, Yaşam > Ayakkabı ve Terlik > Ev Tekstili', 'diger/ev-mutfak'),
    ('carrefour', 'Ev, Yaşam > Bahçe, Kamping ve Barbekü', 'diger/bahce-spor'),
    ('carrefour', 'Ev, Yaşam > Bisiklet ve Spor & Outdoor', 'diger/bahce-spor'),
    ('carrefour', 'Ev, Yaşam > Hırdavat, Aydınlatma ve Piller', 'diger/hirdavat-oto'),
    ('carrefour', 'Ev, Yaşam > Oto Ürünleri', 'diger/hirdavat-oto'),
    ('carrefour', 'Ev, Yaşam > Çanta ve Valiz', 'diger/giyim'),
    ('carrefour', 'Fırın', 'firin'),
    ('carrefour', 'Fırın > Ekmek', 'firin/ekmek'),
    ('carrefour', 'Fırın > Kurabiyeler', 'firin/unlu-mamuller'),
    ('carrefour', 'Fırın > Mantı, Yufka, Tarhana', 'firin/unlu-mamuller'),
    ('carrefour', 'Fırın > Tatlı', 'firin/tatli-pasta'),
    ('carrefour', 'Fırın > Çörekler', 'firin/unlu-mamuller'),
    ('carrefour', 'Hazır Yemek&Donuk Ürünler', 'dondurulmus-hazir'),
    ('carrefour', 'Hazır Yemek&Donuk Ürünler > Meze', 'dondurulmus-hazir/hazir-yemek'),
    ('carrefour', 'Kahvaltılık Ürünler', 'sut-kahvaltilik'),
    ('carrefour', 'Kahvaltılık Ürünler > Zeytin', 'sut-kahvaltilik/zeytin'),
    ('carrefour', 'Kitap, Kırtasiye, Oyuncak', 'diger/kitap-kirtasiye'),
    ('carrefour', 'Kitap, Kırtasiye, Oyuncak > Eğlence, Hobi, Oyuncak', 'diger/oyuncak'),
    ('carrefour', 'Kişisel Bakım', 'kisisel-bakim'),
    ('carrefour', 'Kişisel Bakım > Ağda ve Epilasyon', 'kisisel-bakim/agda'),
    ('carrefour', 'Kişisel Bakım > Ağız Bakım Ürünleri', 'kisisel-bakim/agiz-dis'),
    ('carrefour', 'Kişisel Bakım > Banyo ve Duş Ürünleri', 'kisisel-bakim/dus-banyo'),
    ('carrefour', 'Kişisel Bakım > Cilt Bakım', 'kisisel-bakim/cilt'),
    ('carrefour', 'Kişisel Bakım > Güneş Koruma Ürünleri', 'kisisel-bakim/cilt'),
    ('carrefour', 'Kişisel Bakım > Hijyenik Ped', 'kisisel-bakim/ped'),
    ('carrefour', 'Kişisel Bakım > Kolonyalar', 'kisisel-bakim/kolonya'),
    ('carrefour', 'Kişisel Bakım > Makyaj Ürünleri', 'kisisel-bakim/makyaj'),
    ('carrefour', 'Kişisel Bakım > Parfüm & Deodorant', 'kisisel-bakim/deodorant-parfum'),
    ('carrefour', 'Kişisel Bakım > Saç Bakım Ürünleri', 'kisisel-bakim/sac'),
    ('carrefour', 'Kişisel Bakım > Sağlık Ürünleri', 'kisisel-bakim/saglik'),
    ('carrefour', 'Kişisel Bakım > Tıraş Ürünleri', 'kisisel-bakim/tiras'),
    ('carrefour', 'Meyve, Sebze', 'meyve-sebze'),
    ('carrefour', 'Meyve, Sebze > Meyve', 'meyve-sebze/meyve'),
    ('carrefour', 'Meyve, Sebze > Sebze', 'meyve-sebze/sebze'),
    ('carrefour', 'Meyve, Sebze > Sebze > Otlar', 'meyve-sebze/yesillik'),
    ('carrefour', 'Meyve, Sebze > Sebze > Yeşillikler', 'meyve-sebze/yesillik'),
    ('carrefour', 'Patifour', 'evcil-hayvan'),
    ('carrefour', 'Patifour > Patifour Kedi Ürünleri', 'evcil-hayvan/kedi'),
    ('carrefour', 'Patifour > Patifour Köpek Ürünleri', 'evcil-hayvan/kopek'),
    ('carrefour', 'Pet Shop', 'evcil-hayvan'),
    ('carrefour', 'Pet Shop > Kedi', 'evcil-hayvan/kedi'),
    ('carrefour', 'Pet Shop > Kemirgenler', 'evcil-hayvan/diger'),
    ('carrefour', 'Pet Shop > Kuş', 'evcil-hayvan/diger'),
    ('carrefour', 'Pet Shop > Köpek', 'evcil-hayvan/kopek'),
    ('carrefour', 'Sağlıklı Yaşam', 'saglikli-yasam'),
    ('carrefour', 'Sağlıklı Yaşam > Aktif Yaşam Ürünleri', 'saglikli-yasam/takviye'),
    ('carrefour', 'Sağlıklı Yaşam > Barlar', 'atistirmalik/gofret-bar'),
    ('carrefour', 'Sağlıklı Yaşam > Glutensiz  Ürünler', 'saglikli-yasam/organik-glutensiz'),
    ('carrefour', 'Sağlıklı Yaşam > Organik Ürünler', 'saglikli-yasam/organik-glutensiz'),
    ('carrefour', 'Sağlıklı Yaşam > Tatlandırıcılar & Tatlandırıcılı Ürünler', 'temel-gida/seker'),
    ('carrefour', 'Süt Ürünleri', 'sut-kahvaltilik'),
    ('carrefour', 'Süt Ürünleri > Kahvaltılıklar > Ballar', 'sut-kahvaltilik/bal-recel'),
    ('carrefour', 'Süt Ürünleri > Kahvaltılıklar > Ezmeler', 'sut-kahvaltilik/ezmeler'),
    ('carrefour', 'Süt Ürünleri > Kahvaltılıklar > Fıstık Ezmesi', 'sut-kahvaltilik/ezmeler'),
    ('carrefour', 'Süt Ürünleri > Kahvaltılıklar > Helva', 'sut-kahvaltilik/helva-tahin'),
    ('carrefour', 'Süt Ürünleri > Kahvaltılıklar > Kahvaltılık Gevrek', 'sut-kahvaltilik/gevrek'),
    ('carrefour', 'Süt Ürünleri > Kahvaltılıklar > Krem Çikolata', 'sut-kahvaltilik/ezmeler'),
    ('carrefour', 'Süt Ürünleri > Kahvaltılıklar > Pekmez', 'sut-kahvaltilik/helva-tahin'),
    ('carrefour', 'Süt Ürünleri > Kahvaltılıklar > Reçel', 'sut-kahvaltilik/bal-recel'),
    ('carrefour', 'Süt Ürünleri > Kahvaltılıklar > Tahin', 'sut-kahvaltilik/helva-tahin'),
    ('carrefour', 'Süt Ürünleri > Krema ve Kaymak', 'sut-kahvaltilik/kaymak-krema'),
    ('carrefour', 'Süt Ürünleri > Peynir', 'sut-kahvaltilik/peynir'),
    ('carrefour', 'Süt Ürünleri > Süt', 'sut-kahvaltilik/sut'),
    ('carrefour', 'Süt Ürünleri > Sütlü Tatlı,Puding', 'sut-kahvaltilik/sutlu-tatli'),
    ('carrefour', 'Süt Ürünleri > Tereyağ ve Margarin', 'sut-kahvaltilik/tereyagi-margarin'),
    ('carrefour', 'Süt Ürünleri > Yoğurt', 'sut-kahvaltilik/yogurt'),
    ('carrefour', 'Süt Ürünleri > Yoğurt & Kefir Mayası', 'sut-kahvaltilik/yogurt'),
    ('carrefour', 'Süt Ürünleri > Yumurtalar', 'sut-kahvaltilik/yumurta'),
    ('carrefour', 'Temel Gıda', 'temel-gida'),
    ('carrefour', 'Temel Gıda > Bakliyat', 'temel-gida/bakliyat'),
    ('carrefour', 'Temel Gıda > Dondurulmuş Ürünler', 'dondurulmus-hazir/dondurulmus'),
    ('carrefour', 'Temel Gıda > Konserve', 'temel-gida/konserve'),
    ('carrefour', 'Temel Gıda > Konserve > Salça', 'temel-gida/salca'),
    ('carrefour', 'Temel Gıda > Makarna ve Erişte', 'temel-gida/makarna'),
    ('carrefour', 'Temel Gıda > Paketli Hazır Yemekler', 'dondurulmus-hazir/hazir-yemek'),
    ('carrefour', 'Temel Gıda > Paketli Hazır Yemekler > Çorba', 'temel-gida/corba'),
    ('carrefour', 'Temel Gıda > Pasta Malzemeleri', 'temel-gida/pasta-malzemeleri'),
    ('carrefour', 'Temel Gıda > Salça, Harç ve Bulyon', 'temel-gida/baharat'),
    ('carrefour', 'Temel Gıda > Soslar', 'temel-gida/sos'),
    ('carrefour', 'Temel Gıda > Sıvı Yağlar', 'temel-gida/sivi-yag'),
    ('carrefour', 'Temel Gıda > Tuz ve Baharat', 'temel-gida/baharat'),
    ('carrefour', 'Temel Gıda > Un ve İrmik', 'temel-gida/un'),
    ('carrefour', 'Temel Gıda > Şeker', 'temel-gida/seker'),
    ('carrefour', 'Temizlik Ürünleri', 'temizlik'),
    ('carrefour', 'Temizlik Ürünleri > Bulaşık Yıkama Ürünleri', 'temizlik/bulasik'),
    ('carrefour', 'Temizlik Ürünleri > Bulaşık Yıkama Ürünleri > Bulaşık Süngeri', 'temizlik/malzemeler'),
    ('carrefour', 'Temizlik Ürünleri > Ev Düzenleme', 'temizlik/malzemeler'),
    ('carrefour', 'Temizlik Ürünleri > Genel Temizlik', 'temizlik/genel'),
    ('carrefour', 'Temizlik Ürünleri > Genel Temizlik > Haşere Öldürücüler', 'temizlik/hasere'),
    ('carrefour', 'Temizlik Ürünleri > Kağıt Ürünleri', 'kagit'),
    ('carrefour', 'Temizlik Ürünleri > Kağıt Ürünleri > Islak Mendil', 'kagit/islak-mendil'),
    ('carrefour', 'Temizlik Ürünleri > Kağıt Ürünleri > Kağıt Havlular', 'kagit/kagit-havlu'),
    ('carrefour', 'Temizlik Ürünleri > Kağıt Ürünleri > Kağıt Mendil', 'kagit/pecete-mendil'),
    ('carrefour', 'Temizlik Ürünleri > Kağıt Ürünleri > Peçete', 'kagit/pecete-mendil'),
    ('carrefour', 'Temizlik Ürünleri > Kağıt Ürünleri > Tuvalet Kağıtları', 'kagit/tuvalet-kagidi'),
    ('carrefour', 'Temizlik Ürünleri > Kağıt Ürünleri > Yüzey Temizlik Havlusu', 'temizlik/malzemeler'),
    ('carrefour', 'Temizlik Ürünleri > Oda Kokusu ve Koku Gidericiler', 'temizlik/oda-kokusu'),
    ('carrefour', 'Temizlik Ürünleri > Çakmak ve Ateş Yakma Ürünler', 'diger/ev-mutfak'),
    ('carrefour', 'Temizlik Ürünleri > Çamaşır Yıkama Ürünleri', 'temizlik/camasir'),
    ('carrefour', 'Temizlik Ürünleri > Çöp Torbası', 'temizlik/malzemeler'),
    ('carrefour', 'İçecekler', 'icecek'),
    ('carrefour', 'İçecekler > Gazlı İçecekler', 'icecek/gazli'),
    ('carrefour', 'İçecekler > Gazlı İçecekler > Enerji İçeceği', 'icecek/enerji'),
    ('carrefour', 'İçecekler > Gazsız İçecekler', 'icecek/gazsiz'),
    ('carrefour', 'İçecekler > Gazsız İçecekler > Ayran', 'sut-kahvaltilik/ayran-kefir'),
    ('carrefour', 'İçecekler > Gazsız İçecekler > Kefir', 'sut-kahvaltilik/ayran-kefir'),
    ('carrefour', 'İçecekler > Kahve', 'icecek/kahve'),
    ('carrefour', 'İçecekler > Maden Suyu', 'icecek/maden-suyu'),
    ('carrefour', 'İçecekler > Sporcu İçecekleri', 'icecek/enerji'),
    ('carrefour', 'İçecekler > Su', 'icecek/su'),
    ('carrefour', 'İçecekler > Çay', 'icecek/cay'),

    -- getir ----------------------------------------------------------------------
    ('getir', 'Atıştırmalık', 'atistirmalik'),
    ('getir', 'Atıştırmalık > Bisküvi', 'atistirmalik/biskuvi-kraker'),
    ('getir', 'Atıştırmalık > Cips', 'atistirmalik/cips'),
    ('getir', 'Atıştırmalık > Gofret', 'atistirmalik/gofret-bar'),
    ('getir', 'Atıştırmalık > Kek', 'atistirmalik/kek'),
    ('getir', 'Atıştırmalık > Kraker & Kurabiye', 'atistirmalik/biskuvi-kraker'),
    ('getir', 'Atıştırmalık > Kuruyemiş', 'atistirmalik/kuruyemis'),
    ('getir', 'Atıştırmalık > Paylaşımlık & Draje', 'atistirmalik/cikolata'),
    ('getir', 'Atıştırmalık > Sakız & Şekerleme', 'atistirmalik/sekerleme-sakiz'),
    ('getir', 'Atıştırmalık > Sürülebilir', 'sut-kahvaltilik/ezmeler'),
    ('getir', 'Atıştırmalık > Tablet Çikolata', 'atistirmalik/cikolata'),
    ('getir', 'Atıştırmalık > Tatlı', 'firin/tatli-pasta'),
    ('getir', 'Atıştırmalık > Çikolata Bar', 'atistirmalik/cikolata'),
    ('getir', 'Bebek', 'anne-bebek'),
    ('getir', 'Bebek > Bebek Bakım', 'anne-bebek/bakim'),
    ('getir', 'Bebek > Bebek Bezi', 'anne-bebek/bebek-bezi'),
    ('getir', 'Bebek > Biberon & Emzik', 'anne-bebek/gerecler'),
    ('getir', 'Bebek > Mama', 'anne-bebek/mama'),
    ('getir', 'Cinsel Sağlık', 'kisisel-bakim/saglik'),
    ('getir', 'Dondurma', 'atistirmalik/dondurma'),
    ('getir', 'Et, Tavuk & Balık', 'et-tavuk-balik'),
    ('getir', 'Et, Tavuk & Balık > Balık & Deniz Ürünleri', 'et-tavuk-balik/balik'),
    ('getir', 'Et, Tavuk & Balık > Beyaz Et', 'et-tavuk-balik/beyaz-et'),
    ('getir', 'Et, Tavuk & Balık > Kırmızı Et', 'et-tavuk-balik/kirmizi-et'),
    ('getir', 'Ev & Yaşam', 'diger/ev-mutfak'),
    ('getir', 'Ev & Yaşam > Ayakkabı Bakım', 'temizlik/genel'),
    ('getir', 'Ev & Yaşam > Dergi', 'diger/kitap-kirtasiye'),
    ('getir', 'Ev & Yaşam > Elektrik & Aydınlatma', 'diger/elektronik'),
    ('getir', 'Ev & Yaşam > Hediye Kartı', 'diger/hediye'),
    ('getir', 'Ev & Yaşam > Kırtasiye', 'diger/kitap-kirtasiye'),
    ('getir', 'Ev & Yaşam > Oyun & Oyuncak', 'diger/oyuncak'),
    ('getir', 'Ev & Yaşam > Piknik', 'diger/bahce-spor'),
    ('getir', 'Ev & Yaşam > Pil', 'diger/elektronik'),
    ('getir', 'Ev & Yaşam > Şemsiye', 'diger/giyim'),
    ('getir', 'Ev Bakım', 'temizlik'),
    ('getir', 'Ev Bakım > Bulaşık', 'temizlik/bulasik'),
    ('getir', 'Ev Bakım > Kağıt Ürünleri', 'kagit'),
    ('getir', 'Ev Bakım > Mutfak', 'temizlik/genel'),
    ('getir', 'Ev Bakım > Oda Kokusu', 'temizlik/oda-kokusu'),
    ('getir', 'Ev Bakım > Temizlik', 'temizlik/genel'),
    ('getir', 'Ev Bakım > Çamaşır', 'temizlik/camasir'),
    ('getir', 'Evcil Hayvan', 'evcil-hayvan'),
    ('getir', 'Evcil Hayvan > Kedi', 'evcil-hayvan/kedi'),
    ('getir', 'Evcil Hayvan > Kuş', 'evcil-hayvan/diger'),
    ('getir', 'Evcil Hayvan > Köpek', 'evcil-hayvan/kopek'),
    ('getir', 'Fit & Form', 'saglikli-yasam'),
    ('getir', 'Fit & Form > Bar', 'atistirmalik/gofret-bar'),
    ('getir', 'Fit & Form > Glutensiz', 'saglikli-yasam/organik-glutensiz'),
    ('getir', 'Fit & Form > Granola', 'sut-kahvaltilik/gevrek'),
    ('getir', 'Fit & Form > Kraker & Bisküvi', 'atistirmalik/biskuvi-kraker'),
    ('getir', 'Fit & Form > Vegan', 'saglikli-yasam/vegan'),
    ('getir', 'Fırından', 'firin'),
    ('getir', 'Fırından > Donuk Fırın', 'dondurulmus-hazir/dondurulmus'),
    ('getir', 'Fırından > Glutensiz', 'saglikli-yasam/organik-glutensiz'),
    ('getir', 'Fırından > Taze Fırın', 'firin/ekmek'),
    ('getir', 'Fırından > Unlu Mamüller', 'firin/unlu-mamuller'),
    ('getir', 'Kahvaltılık', 'sut-kahvaltilik'),
    ('getir', 'Kahvaltılık > Bal & Reçel', 'sut-kahvaltilik/bal-recel'),
    ('getir', 'Kahvaltılık > Helva', 'sut-kahvaltilik/helva-tahin'),
    ('getir', 'Kahvaltılık > Kahvaltılık Gevrek', 'sut-kahvaltilik/gevrek'),
    ('getir', 'Kahvaltılık > Sürülebilir', 'sut-kahvaltilik/ezmeler'),
    ('getir', 'Kahvaltılık > Yumurta', 'sut-kahvaltilik/yumurta'),
    ('getir', 'Kahvaltılık > Zeytin', 'sut-kahvaltilik/zeytin'),
    ('getir', 'Kahvaltılık > Çay', 'icecek/cay'),
    ('getir', 'Kahvaltılık > Şarküteri', 'et-tavuk-balik/sarkuteri'),
    ('getir', 'Kişisel Bakım', 'kisisel-bakim'),
    ('getir', 'Kişisel Bakım > Ağda & Tüy Dökücü', 'kisisel-bakim/agda'),
    ('getir', 'Kişisel Bakım > Ağız Bakım', 'kisisel-bakim/agiz-dis'),
    ('getir', 'Kişisel Bakım > Deodorant', 'kisisel-bakim/deodorant-parfum'),
    ('getir', 'Kişisel Bakım > Duş & Banyo', 'kisisel-bakim/dus-banyo'),
    ('getir', 'Kişisel Bakım > Genel Sağlık', 'kisisel-bakim/saglik'),
    ('getir', 'Kişisel Bakım > Hijyenik Ped', 'kisisel-bakim/ped'),
    ('getir', 'Kişisel Bakım > Islak Havlu', 'kagit/islak-mendil'),
    ('getir', 'Kişisel Bakım > Kolonya', 'kisisel-bakim/kolonya'),
    ('getir', 'Kişisel Bakım > Kozmetik', 'kisisel-bakim/makyaj'),
    ('getir', 'Kişisel Bakım > Sabun', 'kisisel-bakim/dus-banyo'),
    ('getir', 'Kişisel Bakım > Saç Bakım', 'kisisel-bakim/sac'),
    ('getir', 'Kişisel Bakım > Saç Boyası', 'kisisel-bakim/sac'),
    ('getir', 'Kişisel Bakım > Tıraş Malzemeleri', 'kisisel-bakim/tiras'),
    ('getir', 'Kişisel Bakım > Vücut & El Bakım', 'kisisel-bakim/cilt'),
    ('getir', 'Meyve & Sebze', 'meyve-sebze'),
    ('getir', 'Meyve & Sebze > Meyve', 'meyve-sebze/meyve'),
    ('getir', 'Meyve & Sebze > Sebze', 'meyve-sebze/sebze'),
    ('getir', 'Meyve & Sebze > Yeşillik', 'meyve-sebze/yesillik'),
    ('getir', 'Pratik Yemek', 'dondurulmus-hazir'),
    ('getir', 'Pratik Yemek > Sandviç', 'dondurulmus-hazir/hazir-yemek'),
    ('getir', 'Pratik Yemek > Taze Yemek', 'dondurulmus-hazir/hazir-yemek'),
    ('getir', 'Pratik Yemek > Vegan', 'saglikli-yasam/vegan'),
    ('getir', 'Pratik Yemek > Çiğ Köfte & Meze', 'dondurulmus-hazir/hazir-yemek'),
    ('getir', 'Su & İçecek', 'icecek'),
    ('getir', 'Su & İçecek > Ayran & Kefir', 'sut-kahvaltilik/ayran-kefir'),
    ('getir', 'Su & İçecek > Buz', 'atistirmalik/dondurma'),
    ('getir', 'Su & İçecek > Enerji İçeceği', 'icecek/enerji'),
    ('getir', 'Su & İçecek > Fonksiyonel İçecekler', 'icecek/gazsiz'),
    ('getir', 'Su & İçecek > Gazlı İçecek', 'icecek/gazli'),
    ('getir', 'Su & İçecek > Kahve', 'icecek/kahve'),
    ('getir', 'Su & İçecek > Maden Suyu', 'icecek/maden-suyu'),
    ('getir', 'Su & İçecek > Meyve Suyu', 'icecek/gazsiz'),
    ('getir', 'Su & İçecek > Soğuk Çay', 'icecek/gazsiz'),
    ('getir', 'Su & İçecek > Su', 'icecek/su'),
    ('getir', 'Su & İçecek > Çay', 'icecek/cay'),
    ('getir', 'Süt Ürünleri', 'sut-kahvaltilik'),
    ('getir', 'Süt Ürünleri > Ayran & Kefir', 'sut-kahvaltilik/ayran-kefir'),
    ('getir', 'Süt Ürünleri > Tereyağı', 'sut-kahvaltilik/tereyagi-margarin'),
    ('getir', 'Süt Ürünleri > Uzun Ömürlü Süt', 'sut-kahvaltilik/sut'),
    ('getir', 'Süt Ürünleri > Yoğurt', 'sut-kahvaltilik/yogurt'),
    ('getir', 'Temel Gıda', 'temel-gida'),
    ('getir', 'Temel Gıda > Baharat', 'temel-gida/baharat'),
    ('getir', 'Temel Gıda > Bakliyat', 'temel-gida/bakliyat'),
    ('getir', 'Temel Gıda > Bulgur', 'temel-gida/bakliyat'),
    ('getir', 'Temel Gıda > Konserve', 'temel-gida/konserve'),
    ('getir', 'Temel Gıda > Makarna', 'temel-gida/makarna'),
    ('getir', 'Temel Gıda > Pasta Malzemeleri', 'temel-gida/pasta-malzemeleri'),
    ('getir', 'Temel Gıda > Pirinç', 'temel-gida/bakliyat'),
    ('getir', 'Temel Gıda > Salça', 'temel-gida/salca'),
    ('getir', 'Temel Gıda > Sirke & Salata Sosu', 'temel-gida/sos'),
    ('getir', 'Temel Gıda > Sos', 'temel-gida/sos'),
    ('getir', 'Temel Gıda > Sıvı Yağ', 'temel-gida/sivi-yag'),
    ('getir', 'Temel Gıda > Tatlı', 'temel-gida/pasta-malzemeleri'),
    ('getir', 'Temel Gıda > Un', 'temel-gida/un'),
    ('getir', 'Temel Gıda > Zeytinyağı', 'temel-gida/sivi-yag'),
    ('getir', 'Temel Gıda > Çorba', 'temel-gida/corba'),
    ('getir', 'Temel Gıda > Şeker', 'temel-gida/seker'),

    -- migros ---------------------------------------------------------------------
    ('migros', 'Atıştırmalık', 'atistirmalik'),
    ('migros', 'Atıştırmalık > Bar, Kaplamalılar', 'atistirmalik/gofret-bar'),
    ('migros', 'Atıştırmalık > Bisküvi', 'atistirmalik/biskuvi-kraker'),
    ('migros', 'Atıştırmalık > Cips', 'atistirmalik/cips'),
    ('migros', 'Atıştırmalık > Gofret', 'atistirmalik/gofret-bar'),
    ('migros', 'Atıştırmalık > Kek', 'atistirmalik/kek'),
    ('migros', 'Atıştırmalık > Kraker', 'atistirmalik/biskuvi-kraker'),
    ('migros', 'Atıştırmalık > Kuru Meyve', 'atistirmalik/kuruyemis'),
    ('migros', 'Atıştırmalık > Kuruyemiş', 'atistirmalik/kuruyemis'),
    ('migros', 'Atıştırmalık > Mısır ve Pirinç Patlağı', 'atistirmalik/cips'),
    ('migros', 'Atıştırmalık > Sakız', 'atistirmalik/sekerleme-sakiz'),
    ('migros', 'Atıştırmalık > Çikolata', 'atistirmalik/cikolata'),
    ('migros', 'Atıştırmalık > Şekerleme', 'atistirmalik/sekerleme-sakiz'),
    ('migros', 'Bebek', 'anne-bebek'),
    ('migros', 'Bebek > Anne Ürünleri', 'anne-bebek/bakim'),
    ('migros', 'Bebek > Bebek Bakım', 'anne-bebek/bakim'),
    ('migros', 'Bebek > Bebek Banyo', 'anne-bebek/bakim'),
    ('migros', 'Bebek > Bebek Beslenme', 'anne-bebek/mama'),
    ('migros', 'Bebek > Bebek Beslenme > Bebek Beslenme Araçları', 'anne-bebek/gerecler'),
    ('migros', 'Bebek > Bebek Bezi', 'anne-bebek/bebek-bezi'),
    ('migros', 'Bebek > Bebek Deterjanı ve Yumuşatıcısı', 'anne-bebek/bakim'),
    ('migros', 'Bebek > Bebek Tekstil', 'anne-bebek/gerecler'),
    ('migros', 'Bebek > Mama Sandalyesi', 'anne-bebek/gerecler'),
    ('migros', 'Deterjan, Temizlik', 'temizlik'),
    ('migros', 'Deterjan, Temizlik > Banyo Gereçleri', 'diger/ev-mutfak'),
    ('migros', 'Deterjan, Temizlik > Bulaşık Yıkama', 'temizlik/bulasik'),
    ('migros', 'Deterjan, Temizlik > Genel Temizlik', 'temizlik/genel'),
    ('migros', 'Deterjan, Temizlik > Genel Temizlik > Hava Temizleyiciler', 'temizlik/oda-kokusu'),
    ('migros', 'Deterjan, Temizlik > Genel Temizlik > Haşere Öldürücüler', 'temizlik/hasere'),
    ('migros', 'Deterjan, Temizlik > Temizlik Malzemeleri', 'temizlik/malzemeler'),
    ('migros', 'Deterjan, Temizlik > Çamaşır Gereçleri', 'temizlik/malzemeler'),
    ('migros', 'Deterjan, Temizlik > Çamaşır Yıkama', 'temizlik/camasir'),
    ('migros', 'Deterjan, Temizlik > Çöp Poşeti', 'temizlik/malzemeler'),
    ('migros', 'Dondurma', 'atistirmalik/dondurma'),
    ('migros', 'Dondurulmuş Gıda', 'dondurulmus-hazir/dondurulmus'),
    ('migros', 'Elektronik', 'diger/elektronik'),
    ('migros', 'Et, Tavuk, Balık', 'et-tavuk-balik'),
    ('migros', 'Et, Tavuk, Balık > Balık, Deniz Ürünleri', 'et-tavuk-balik/balik'),
    ('migros', 'Et, Tavuk, Balık > Beyaz Et', 'et-tavuk-balik/beyaz-et'),
    ('migros', 'Et, Tavuk, Balık > Et Şarküteri', 'et-tavuk-balik/sarkuteri'),
    ('migros', 'Et, Tavuk, Balık > Kırmızı Et', 'et-tavuk-balik/kirmizi-et'),
    ('migros', 'Ev, Yaşam', 'diger/ev-mutfak'),
    ('migros', 'Ev, Yaşam > Ampul', 'diger/elektronik'),
    ('migros', 'Ev, Yaşam > Bahçe ve Piknik Malzemeleri', 'diger/bahce-spor'),
    ('migros', 'Ev, Yaşam > Dijital Kodlar, Kartlar', 'diger/hediye'),
    ('migros', 'Ev, Yaşam > Hırdavat', 'diger/hirdavat-oto'),
    ('migros', 'Ev, Yaşam > Mobilya, Dekorasyon > Bahçe Mobilyası', 'diger/bahce-spor'),
    ('migros', 'Ev, Yaşam > Mobilya, Dekorasyon > Parti Malzemeleri', 'diger/hediye'),
    ('migros', 'Ev, Yaşam > Moda, Tekstil', 'diger/giyim'),
    ('migros', 'Ev, Yaşam > Oto Aksesuar', 'diger/hirdavat-oto'),
    ('migros', 'Ev, Yaşam > Pil', 'diger/elektronik'),
    ('migros', 'Ev, Yaşam > Spor, Outdoor', 'diger/bahce-spor'),
    ('migros', 'Evcil Hayvan', 'evcil-hayvan'),
    ('migros', 'Evcil Hayvan > Kedi', 'evcil-hayvan/kedi'),
    ('migros', 'Evcil Hayvan > Kedi Tarağı, Fırçası', 'evcil-hayvan/kedi'),
    ('migros', 'Evcil Hayvan > Kuş', 'evcil-hayvan/diger'),
    ('migros', 'Evcil Hayvan > Köpek', 'evcil-hayvan/kopek'),
    ('migros', 'Evcil Hayvan > Köpek Bakım Ürünleri', 'evcil-hayvan/kopek'),
    ('migros', 'Evcil Hayvan > Köpek Tuvaleti, Eğitim Ürünleri', 'evcil-hayvan/kopek'),
    ('migros', 'Evcil Hayvan > Tavşan Yemi', 'evcil-hayvan/diger'),
    ('migros', 'Fırın, Pastane', 'firin'),
    ('migros', 'Fırın, Pastane > Ekmek', 'firin/ekmek'),
    ('migros', 'Fırın, Pastane > Galeta, Grissini, Gevrek', 'firin/unlu-mamuller'),
    ('migros', 'Fırın, Pastane > Kuru Pasta', 'firin/unlu-mamuller'),
    ('migros', 'Fırın, Pastane > Pasta', 'firin/tatli-pasta'),
    ('migros', 'Fırın, Pastane > Sabah Sıcakları', 'firin/unlu-mamuller'),
    ('migros', 'Fırın, Pastane > Tatlı', 'firin/tatli-pasta'),
    ('migros', 'Fırın, Pastane > Tatlı > Toz Tatlılar', 'temel-gida/pasta-malzemeleri'),
    ('migros', 'Hazır Yemek, Meze', 'dondurulmus-hazir/hazir-yemek'),
    ('migros', 'Hazır Yemek, Meze > Sıvı Çorba', 'temel-gida/corba'),
    ('migros', 'Hazır Yemek, Meze > Tarhana', 'temel-gida/corba'),
    ('migros', 'Hazır Yemek, Meze > Toz Çorba', 'temel-gida/corba'),
    ('migros', 'Kağıt, Islak Mendil', 'kagit'),
    ('migros', 'Kağıt, Islak Mendil > Islak Mendil', 'kagit/islak-mendil'),
    ('migros', 'Kağıt, Islak Mendil > Kağıt Havlu', 'kagit/kagit-havlu'),
    ('migros', 'Kağıt, Islak Mendil > Kağıt Mendil', 'kagit/pecete-mendil'),
    ('migros', 'Kağıt, Islak Mendil > Peçete', 'kagit/pecete-mendil'),
    ('migros', 'Kağıt, Islak Mendil > Temizlik Havlusu', 'temizlik/malzemeler'),
    ('migros', 'Kağıt, Islak Mendil > Tuvalet Kağıdı', 'kagit/tuvalet-kagidi'),
    ('migros', 'Kitap, Kırtasiye, Oyuncak', 'diger/kitap-kirtasiye'),
    ('migros', 'Kitap, Kırtasiye, Oyuncak > Oyuncak', 'diger/oyuncak'),
    ('migros', 'Kişisel Bakım, Kozmetik, Sağlık', 'kisisel-bakim'),
    ('migros', 'Kişisel Bakım, Kozmetik, Sağlık > Ağda, Epilasyon', 'kisisel-bakim/agda'),
    ('migros', 'Kişisel Bakım, Kozmetik, Sağlık > Ağız Bakım Ürünleri', 'kisisel-bakim/agiz-dis'),
    ('migros', 'Kişisel Bakım, Kozmetik, Sağlık > Bebek Kolonyası', 'kisisel-bakim/kolonya'),
    ('migros', 'Kişisel Bakım, Kozmetik, Sağlık > Cilt Bakımı', 'kisisel-bakim/cilt'),
    ('migros', 'Kişisel Bakım, Kozmetik, Sağlık > Duş, Banyo, Sabun', 'kisisel-bakim/dus-banyo'),
    ('migros', 'Kişisel Bakım, Kozmetik, Sağlık > Güneş Bakım', 'kisisel-bakim/cilt'),
    ('migros', 'Kişisel Bakım, Kozmetik, Sağlık > Hijyenik Ped', 'kisisel-bakim/ped'),
    ('migros', 'Kişisel Bakım, Kozmetik, Sağlık > Kolonya', 'kisisel-bakim/kolonya'),
    ('migros', 'Kişisel Bakım, Kozmetik, Sağlık > Makyaj', 'kisisel-bakim/makyaj'),
    ('migros', 'Kişisel Bakım, Kozmetik, Sağlık > Parfüm, Deodorant', 'kisisel-bakim/deodorant-parfum'),
    ('migros', 'Kişisel Bakım, Kozmetik, Sağlık > Saç Bakım', 'kisisel-bakim/sac'),
    ('migros', 'Kişisel Bakım, Kozmetik, Sağlık > Sağlık Ürünleri', 'kisisel-bakim/saglik'),
    ('migros', 'Kişisel Bakım, Kozmetik, Sağlık > Sağlık Ürünleri > Sporcu Takviyeleri', 'saglikli-yasam/takviye'),
    ('migros', 'Kişisel Bakım, Kozmetik, Sağlık > Sağlık Ürünleri > Takviye Edici Gıda', 'saglikli-yasam/takviye'),
    ('migros', 'Kişisel Bakım, Kozmetik, Sağlık > Tıraş Malzemeleri', 'kisisel-bakim/tiras'),
    ('migros', 'Meyve, Sebze', 'meyve-sebze'),
    ('migros', 'Meyve, Sebze > Meyve', 'meyve-sebze/meyve'),
    ('migros', 'Meyve, Sebze > Mikro Filiz ve Yaşayan Bitkiler', 'meyve-sebze/yesillik'),
    ('migros', 'Meyve, Sebze > Sebze', 'meyve-sebze/sebze'),
    ('migros', 'Meyve, Sebze > Sebze > Otlar, Yeşillikler', 'meyve-sebze/yesillik'),
    ('migros', 'Süt, Kahvaltılık', 'sut-kahvaltilik'),
    ('migros', 'Süt, Kahvaltılık > Kahvaltılıklar > Bal', 'sut-kahvaltilik/bal-recel'),
    ('migros', 'Süt, Kahvaltılık > Kahvaltılıklar > Helva, Tahin, Pekmez', 'sut-kahvaltilik/helva-tahin'),
    ('migros', 'Süt, Kahvaltılık > Kahvaltılıklar > Kahvaltılık Gevrek', 'sut-kahvaltilik/gevrek'),
    ('migros', 'Süt, Kahvaltılık > Kahvaltılıklar > Kahvaltılık Sos', 'sut-kahvaltilik/ezmeler'),
    ('migros', 'Süt, Kahvaltılık > Kahvaltılıklar > Krem Çikolata, Ezmeler', 'sut-kahvaltilik/ezmeler'),
    ('migros', 'Süt, Kahvaltılık > Kahvaltılıklar > Reçel, Marmelat', 'sut-kahvaltilik/bal-recel'),
    ('migros', 'Süt, Kahvaltılık > Margarin', 'sut-kahvaltilik/tereyagi-margarin'),
    ('migros', 'Süt, Kahvaltılık > Peynir', 'sut-kahvaltilik/peynir'),
    ('migros', 'Süt, Kahvaltılık > Süt', 'sut-kahvaltilik/sut'),
    ('migros', 'Süt, Kahvaltılık > Sütlü Tatlı, Krema', 'sut-kahvaltilik/sutlu-tatli'),
    ('migros', 'Süt, Kahvaltılık > Sütlü Tatlı, Krema > Kaymak', 'sut-kahvaltilik/kaymak-krema'),
    ('migros', 'Süt, Kahvaltılık > Sütlü Tatlı, Krema > Krema', 'sut-kahvaltilik/kaymak-krema'),
    ('migros', 'Süt, Kahvaltılık > Tereyağı', 'sut-kahvaltilik/tereyagi-margarin'),
    ('migros', 'Süt, Kahvaltılık > Yoğurt', 'sut-kahvaltilik/yogurt'),
    ('migros', 'Süt, Kahvaltılık > Yumurta', 'sut-kahvaltilik/yumurta'),
    ('migros', 'Süt, Kahvaltılık > Zeytin', 'sut-kahvaltilik/zeytin'),
    ('migros', 'Temel Gıda', 'temel-gida'),
    ('migros', 'Temel Gıda > Bakliyat', 'temel-gida/bakliyat'),
    ('migros', 'Temel Gıda > Bitkisel Peynir Alternatifleri', 'saglikli-yasam/vegan'),
    ('migros', 'Temel Gıda > Bitkisel Tozlar', 'saglikli-yasam'),
    ('migros', 'Temel Gıda > Et Bulyon', 'temel-gida/baharat'),
    ('migros', 'Temel Gıda > Hamur, Pasta Malzemeleri', 'temel-gida/pasta-malzemeleri'),
    ('migros', 'Temel Gıda > Konserve', 'temel-gida/konserve'),
    ('migros', 'Temel Gıda > Konserve > Salça', 'temel-gida/salca'),
    ('migros', 'Temel Gıda > Makarnalar', 'temel-gida/makarna'),
    ('migros', 'Temel Gıda > Sos', 'temel-gida/sos'),
    ('migros', 'Temel Gıda > Sıvı Yağ', 'temel-gida/sivi-yag'),
    ('migros', 'Temel Gıda > Tavuk Bulyon', 'temel-gida/baharat'),
    ('migros', 'Temel Gıda > Tofu', 'saglikli-yasam/vegan'),
    ('migros', 'Temel Gıda > Tuz, Baharat, Harç', 'temel-gida/baharat'),
    ('migros', 'Temel Gıda > Un', 'temel-gida/un'),
    ('migros', 'Temel Gıda > Yufka', 'firin/unlu-mamuller'),
    ('migros', 'Temel Gıda > Özel Beslenme Ürünleri', 'saglikli-yasam'),
    ('migros', 'Temel Gıda > Şeker', 'temel-gida/seker'),
    ('migros', 'Temel Gıda > Şeker Alternatifleri, Tatlandırıcılar', 'temel-gida/seker'),
    ('migros', 'Çiçek', 'diger/hediye'),
    ('migros', 'İçecek', 'icecek'),
    ('migros', 'İçecek > Gazlı İçecek', 'icecek/gazli'),
    ('migros', 'İçecek > Gazlı İçecek > Enerji İçeceği', 'icecek/enerji'),
    ('migros', 'İçecek > Gazsız İçecek', 'icecek/gazsiz'),
    ('migros', 'İçecek > Gazsız İçecek > Ayran', 'sut-kahvaltilik/ayran-kefir'),
    ('migros', 'İçecek > Gazsız İçecek > Kefir', 'sut-kahvaltilik/ayran-kefir'),
    ('migros', 'İçecek > Gazsız İçecek > Sporcu İçecekleri', 'icecek/enerji'),
    ('migros', 'İçecek > Kahve', 'icecek/kahve'),
    ('migros', 'İçecek > Maden Suyu', 'icecek/maden-suyu'),
    ('migros', 'İçecek > Su', 'icecek/su'),
    ('migros', 'İçecek > Çay', 'icecek/cay'),
    ('migros', 'İçecek > Çay > Soğuk Çay', 'icecek/gazsiz'),

    -- sok ------------------------------------------------------------------------
    ('sok', 'Anne-Bebek ve Çocuk', 'anne-bebek'),
    ('sok', 'Anne-Bebek ve Çocuk > Bebek Bakım Ürünleri', 'anne-bebek/bakim'),
    ('sok', 'Anne-Bebek ve Çocuk > Bebek Bezi', 'anne-bebek/bebek-bezi'),
    ('sok', 'Anne-Bebek ve Çocuk > Bebek Bisküvisi', 'anne-bebek/mama'),
    ('sok', 'Anne-Bebek ve Çocuk > Bebek Deterjan ve Yumuşatıcısı', 'anne-bebek/bakim'),
    ('sok', 'Anne-Bebek ve Çocuk > Bebek Gereçleri', 'anne-bebek/gerecler'),
    ('sok', 'Anne-Bebek ve Çocuk > Bebek Islak Havlu ve Mendil', 'anne-bebek/bakim'),
    ('sok', 'Anne-Bebek ve Çocuk > Bebek Mama', 'anne-bebek/mama'),
    ('sok', 'Anne-Bebek ve Çocuk > Bebek Şampuanı', 'anne-bebek/bakim'),
    ('sok', 'Anne-Bebek ve Çocuk > Külot Bez', 'anne-bebek/bebek-bezi'),
    ('sok', 'Anne-Bebek ve Çocuk > Oyuncak', 'diger/oyuncak'),
    ('sok', 'Anne-Bebek ve Çocuk > Çocuk Kitapları', 'diger/kitap-kirtasiye'),
    ('sok', 'Atıştırmalıklar', 'atistirmalik'),
    ('sok', 'Atıştırmalıklar > Bisküvi', 'atistirmalik/biskuvi-kraker'),
    ('sok', 'Atıştırmalıklar > Cips', 'atistirmalik/cips'),
    ('sok', 'Atıştırmalıklar > Draje', 'atistirmalik/cikolata'),
    ('sok', 'Atıştırmalıklar > Gofret', 'atistirmalik/gofret-bar'),
    ('sok', 'Atıştırmalıklar > Kek', 'atistirmalik/kek'),
    ('sok', 'Atıştırmalıklar > Kraker ve Tuzlu Bisküvi', 'atistirmalik/biskuvi-kraker'),
    ('sok', 'Atıştırmalıklar > Kuruyemiş', 'atistirmalik/kuruyemis'),
    ('sok', 'Atıştırmalıklar > Light Ürünler ve Protein Bar', 'atistirmalik/gofret-bar'),
    ('sok', 'Atıştırmalıklar > Sakız', 'atistirmalik/sekerleme-sakiz'),
    ('sok', 'Atıştırmalıklar > Çikolata', 'atistirmalik/cikolata'),
    ('sok', 'Atıştırmalıklar > Şekerleme', 'atistirmalik/sekerleme-sakiz'),
    ('sok', 'Dondurma', 'atistirmalik/dondurma'),
    ('sok', 'Dondurulmuş Ürünler', 'dondurulmus-hazir/dondurulmus'),
    ('sok', 'Ekmek ve Pastane', 'firin'),
    ('sok', 'Ekmek ve Pastane > Ekmek', 'firin/ekmek'),
    ('sok', 'Ekmek ve Pastane > Galeta ve Grissini', 'firin/unlu-mamuller'),
    ('sok', 'Ekmek ve Pastane > Hamur ve Pasta Malzemeleri', 'temel-gida/pasta-malzemeleri'),
    ('sok', 'Ekmek ve Pastane > Katmer, Lavaş ve Bazlama', 'firin/ekmek'),
    ('sok', 'Ekmek ve Pastane > Kurabiye, Kuruvasan, Simit', 'firin/unlu-mamuller'),
    ('sok', 'Ekmek ve Pastane > Paketli Ekmekler', 'firin/ekmek'),
    ('sok', 'Ekmek ve Pastane > Unlu Mamüller', 'firin/unlu-mamuller'),
    ('sok', 'Elektronik', 'diger/elektronik'),
    ('sok', 'Et ve Tavuk ve Şarküteri', 'et-tavuk-balik'),
    ('sok', 'Et ve Tavuk ve Şarküteri > Beyaz Et', 'et-tavuk-balik/beyaz-et'),
    ('sok', 'Et ve Tavuk ve Şarküteri > Füme Ürünler', 'et-tavuk-balik/sarkuteri'),
    ('sok', 'Et ve Tavuk ve Şarküteri > Jambon Ürünleri', 'et-tavuk-balik/sarkuteri'),
    ('sok', 'Et ve Tavuk ve Şarküteri > Kavurma', 'et-tavuk-balik/sarkuteri'),
    ('sok', 'Et ve Tavuk ve Şarküteri > Kırmızı Et', 'et-tavuk-balik/kirmizi-et'),
    ('sok', 'Et ve Tavuk ve Şarküteri > Paketli Beyaz Et', 'et-tavuk-balik/beyaz-et'),
    ('sok', 'Et ve Tavuk ve Şarküteri > Pastırma', 'et-tavuk-balik/sarkuteri'),
    ('sok', 'Et ve Tavuk ve Şarküteri > Salam', 'et-tavuk-balik/sarkuteri'),
    ('sok', 'Et ve Tavuk ve Şarküteri > Sosis', 'et-tavuk-balik/sarkuteri'),
    ('sok', 'Et ve Tavuk ve Şarküteri > Sucuk', 'et-tavuk-balik/sarkuteri'),
    ('sok', 'Et ve Tavuk ve Şarküteri > Yumurta', 'sut-kahvaltilik/yumurta'),
    ('sok', 'Ev ve Yaşam', 'diger/ev-mutfak'),
    ('sok', 'Ev ve Yaşam > Bahçe ve Çiçek', 'diger/bahce-spor'),
    ('sok', 'Ev ve Yaşam > Hırdavat', 'diger/hirdavat-oto'),
    ('sok', 'Ev ve Yaşam > Kamp ve Piknik', 'diger/bahce-spor'),
    ('sok', 'Ev ve Yaşam > Kitap ve Dergi', 'diger/kitap-kirtasiye'),
    ('sok', 'Ev ve Yaşam > Okul ve Kırtasiye', 'diger/kitap-kirtasiye'),
    ('sok', 'Ev ve Yaşam > Otomobil ve Motorsiklet', 'diger/hirdavat-oto'),
    ('sok', 'Ev ve Yaşam > Parti Malzemeleri', 'diger/hediye'),
    ('sok', 'Ev ve Yaşam > Spor Ürünleri', 'diger/bahce-spor'),
    ('sok', 'Ev ve Yaşam > Tatil ve Deniz', 'diger/bahce-spor'),
    ('sok', 'Ev ve Yaşam > Çöp Torbası, Streç ve Folyo', 'temizlik/malzemeler'),
    ('sok', 'Evcil Dostlar', 'evcil-hayvan/diger'),
    ('sok', 'Evcil Dostlar > Kedi Kumu ve Poşet', 'evcil-hayvan/kedi'),
    ('sok', 'Evcil Dostlar > Kedi Maması', 'evcil-hayvan/kedi'),
    ('sok', 'Evcil Dostlar > Köpek Maması', 'evcil-hayvan/kopek'),
    ('sok', 'Giyim-Ayakkabı ve Aksesuar', 'diger/giyim'),
    ('sok', 'Kahvaltılık', 'sut-kahvaltilik'),
    ('sok', 'Kahvaltılık > Bal', 'sut-kahvaltilik/bal-recel'),
    ('sok', 'Kahvaltılık > Kahvaltılık Gevrek', 'sut-kahvaltilik/gevrek'),
    ('sok', 'Kahvaltılık > Kahvaltılık Soslar', 'sut-kahvaltilik/ezmeler'),
    ('sok', 'Kahvaltılık > Kahve', 'icecek/kahve'),
    ('sok', 'Kahvaltılık > Krem Çikolata ve Ezme', 'sut-kahvaltilik/ezmeler'),
    ('sok', 'Kahvaltılık > Reçel', 'sut-kahvaltilik/bal-recel'),
    ('sok', 'Kahvaltılık > Tahin, Pekmez ve Helva', 'sut-kahvaltilik/helva-tahin'),
    ('sok', 'Kahvaltılık > Zeytin', 'sut-kahvaltilik/zeytin'),
    ('sok', 'Kahvaltılık > Çay', 'icecek/cay'),
    ('sok', 'Kağıt Ürünler', 'kagit'),
    ('sok', 'Kağıt Ürünler > Islak Havlu ve Mendil', 'kagit/islak-mendil'),
    ('sok', 'Kağıt Ürünler > Kağıt Havlu', 'kagit/kagit-havlu'),
    ('sok', 'Kağıt Ürünler > Kağıt Mendil', 'kagit/pecete-mendil'),
    ('sok', 'Kağıt Ürünler > Peçete', 'kagit/pecete-mendil'),
    ('sok', 'Kağıt Ürünler > Temizlik Havlusu', 'temizlik/malzemeler'),
    ('sok', 'Kağıt Ürünler > Tuvalet Kağıdı', 'kagit/tuvalet-kagidi'),
    ('sok', 'Kağıt Ürünler > Yatak Örtüsü-Koruyucu', 'kisisel-bakim/saglik'),
    ('sok', 'Kişisel Bakım ve Kozmetik', 'kisisel-bakim'),
    ('sok', 'Kişisel Bakım ve Kozmetik > Ağız Bakım', 'kisisel-bakim/agiz-dis'),
    ('sok', 'Kişisel Bakım ve Kozmetik > Banyo ve Sabun', 'kisisel-bakim/dus-banyo'),
    ('sok', 'Kişisel Bakım ve Kozmetik > Deodorant ve Parfüm', 'kisisel-bakim/deodorant-parfum'),
    ('sok', 'Kişisel Bakım ve Kozmetik > Epilasyon ve Ağda', 'kisisel-bakim/agda'),
    ('sok', 'Kişisel Bakım ve Kozmetik > Erkek Bakım ve Tıraş', 'kisisel-bakim/tiras'),
    ('sok', 'Kişisel Bakım ve Kozmetik > Güneş Kremleri', 'kisisel-bakim/cilt'),
    ('sok', 'Kişisel Bakım ve Kozmetik > Hasta Bezi', 'kisisel-bakim/saglik'),
    ('sok', 'Kişisel Bakım ve Kozmetik > Hijyenik Ped', 'kisisel-bakim/ped'),
    ('sok', 'Kişisel Bakım ve Kozmetik > Kolonya', 'kisisel-bakim/kolonya'),
    ('sok', 'Kişisel Bakım ve Kozmetik > Makyaj', 'kisisel-bakim/makyaj'),
    ('sok', 'Kişisel Bakım ve Kozmetik > Saç Bakım', 'kisisel-bakim/sac'),
    ('sok', 'Kişisel Bakım ve Kozmetik > Saç Boyası', 'kisisel-bakim/sac'),
    ('sok', 'Kişisel Bakım ve Kozmetik > Saç Şekillendirici', 'kisisel-bakim/sac'),
    ('sok', 'Kişisel Bakım ve Kozmetik > Sağlık Ürünleri', 'kisisel-bakim/saglik'),
    ('sok', 'Kişisel Bakım ve Kozmetik > Yüz, Vücut, El Bakım ve Krem', 'kisisel-bakim/cilt'),
    ('sok', 'Kişisel Bakım ve Kozmetik > Şampuan', 'kisisel-bakim/sac'),
    ('sok', 'Meyve ve Sebze', 'meyve-sebze'),
    ('sok', 'Meyve ve Sebze > Hurmalar', 'atistirmalik/kuruyemis'),
    ('sok', 'Meyve ve Sebze > Kurutulmuş  Meyve ve Sebze', 'atistirmalik/kuruyemis'),
    ('sok', 'Meyve ve Sebze > Meyve', 'meyve-sebze/meyve'),
    ('sok', 'Meyve ve Sebze > Narenciye', 'meyve-sebze/meyve'),
    ('sok', 'Meyve ve Sebze > Patates, Soğan, Sarımsak', 'meyve-sebze/sebze'),
    ('sok', 'Meyve ve Sebze > Sebze', 'meyve-sebze/sebze'),
    ('sok', 'Meyve ve Sebze > Yeşillikler ve Otlar', 'meyve-sebze/yesillik'),
    ('sok', 'Süt ve Süt Ürünleri', 'sut-kahvaltilik'),
    ('sok', 'Süt ve Süt Ürünleri > Ayran', 'sut-kahvaltilik/ayran-kefir'),
    ('sok', 'Süt ve Süt Ürünleri > Beyaz Peynir', 'sut-kahvaltilik/peynir'),
    ('sok', 'Süt ve Süt Ürünleri > Kaymak ve Krema', 'sut-kahvaltilik/kaymak-krema'),
    ('sok', 'Süt ve Süt Ürünleri > Kaşar Peynir', 'sut-kahvaltilik/peynir'),
    ('sok', 'Süt ve Süt Ürünleri > Kefir', 'sut-kahvaltilik/ayran-kefir'),
    ('sok', 'Süt ve Süt Ürünleri > Krem Peynir', 'sut-kahvaltilik/peynir'),
    ('sok', 'Süt ve Süt Ürünleri > Margarin', 'sut-kahvaltilik/tereyagi-margarin'),
    ('sok', 'Süt ve Süt Ürünleri > Süt', 'sut-kahvaltilik/sut'),
    ('sok', 'Süt ve Süt Ürünleri > Tatlı ve Puding', 'sut-kahvaltilik/sutlu-tatli'),
    ('sok', 'Süt ve Süt Ürünleri > Tereyağ', 'sut-kahvaltilik/tereyagi-margarin'),
    ('sok', 'Süt ve Süt Ürünleri > Yoğurt', 'sut-kahvaltilik/yogurt'),
    ('sok', 'Süt ve Süt Ürünleri > Yöresel Peynir', 'sut-kahvaltilik/peynir'),
    ('sok', 'Temizlik', 'temizlik'),
    ('sok', 'Temizlik > Banyo ve Sabun', 'kisisel-bakim/dus-banyo'),
    ('sok', 'Temizlik > Bulaşık', 'temizlik/bulasik'),
    ('sok', 'Temizlik > Ev ve Yüzey Temizleyicileri', 'temizlik/genel'),
    ('sok', 'Temizlik > Genel Temizlik Malzemeleri', 'temizlik/malzemeler'),
    ('sok', 'Temizlik > Haşere Kovar', 'temizlik/hasere'),
    ('sok', 'Temizlik > Oda Kokuları', 'temizlik/oda-kokusu'),
    ('sok', 'Temizlik > Temizlik Bezleri', 'temizlik/malzemeler'),
    ('sok', 'Temizlik > Temizlik Havlusu', 'temizlik/malzemeler'),
    ('sok', 'Temizlik > Çamaşır', 'temizlik/camasir'),
    ('sok', 'Temizlik > Çamaşır Suyu', 'temizlik/camasir'),
    ('sok', 'Yemeklik Malzemeler', 'temel-gida'),
    ('sok', 'Yemeklik Malzemeler > Bakliyat', 'temel-gida/bakliyat'),
    ('sok', 'Yemeklik Malzemeler > Fırından Sıcak', 'firin/unlu-mamuller'),
    ('sok', 'Yemeklik Malzemeler > Hamur ve Pasta Malzemeleri', 'temel-gida/pasta-malzemeleri'),
    ('sok', 'Yemeklik Malzemeler > Hazır Yemek ve Meze', 'dondurulmus-hazir/hazir-yemek'),
    ('sok', 'Yemeklik Malzemeler > Hazır Yemek-Meze', 'dondurulmus-hazir/hazir-yemek'),
    ('sok', 'Yemeklik Malzemeler > Ketçap-Mayonez-Hardal', 'temel-gida/sos'),
    ('sok', 'Yemeklik Malzemeler > Konserve', 'temel-gida/konserve'),
    ('sok', 'Yemeklik Malzemeler > Makarna ve Mantı', 'temel-gida/makarna'),
    ('sok', 'Yemeklik Malzemeler > Margarin', 'sut-kahvaltilik/tereyagi-margarin'),
    ('sok', 'Yemeklik Malzemeler > Mutfak Şeker', 'temel-gida/seker'),
    ('sok', 'Yemeklik Malzemeler > Pirinç ve Bulgur', 'temel-gida/bakliyat'),
    ('sok', 'Yemeklik Malzemeler > Salça', 'temel-gida/salca'),
    ('sok', 'Yemeklik Malzemeler > Soslar', 'temel-gida/sos'),
    ('sok', 'Yemeklik Malzemeler > Sıvı Yağlar', 'temel-gida/sivi-yag'),
    ('sok', 'Yemeklik Malzemeler > Turşu', 'temel-gida/konserve'),
    ('sok', 'Yemeklik Malzemeler > Tuz, Baharat', 'temel-gida/baharat'),
    ('sok', 'Yemeklik Malzemeler > Tuz, Baharat, Bulyon ve Harç', 'temel-gida/baharat'),
    ('sok', 'Yemeklik Malzemeler > Un', 'temel-gida/un'),
    ('sok', 'Yemeklik Malzemeler > Çorba', 'temel-gida/corba'),
    ('sok', 'İçecek', 'icecek'),
    ('sok', 'İçecek > Boza ve Malt İçecekler', 'icecek/gazsiz'),
    ('sok', 'İçecek > Enerji İçeceği', 'icecek/enerji'),
    ('sok', 'İçecek > Fonksiyonel İçecekler', 'icecek/gazsiz'),
    ('sok', 'İçecek > Gazoz', 'icecek/gazli'),
    ('sok', 'İçecek > Kahve', 'icecek/kahve'),
    ('sok', 'İçecek > Kola', 'icecek/gazli'),
    ('sok', 'İçecek > Limonata, Şalgam ve Şerbet', 'icecek/gazsiz'),
    ('sok', 'İçecek > Maden Suyu', 'icecek/maden-suyu'),
    ('sok', 'İçecek > Meyve Suyu', 'icecek/gazsiz'),
    ('sok', 'İçecek > Soğuk Kahve', 'icecek/kahve'),
    ('sok', 'İçecek > Soğuk Toz İçecekler', 'icecek/gazsiz'),
    ('sok', 'İçecek > Soğuk Çay', 'icecek/gazsiz'),
    ('sok', 'İçecek > Su', 'icecek/su'),
    ('sok', 'İçecek > Çay', 'icecek/cay');

-- A typo in a slug or market name fails the whole file instead of dropping a rule
DO $$
DECLARE bad TEXT;
BEGIN
    SELECT string_agg(format('%s | %s | %s', r.market, r.market_category, r.slug), E'\n')
    INTO bad
    FROM rules r
    LEFT JOIN markets m ON m.name = r.market
    LEFT JOIN categories c ON c.slug = r.slug
    WHERE m.id IS NULL OR c.id IS NULL;
    IF bad IS NOT NULL THEN
        RAISE EXCEPTION E'Rules with an unknown market or slug:\n%', bad;
    END IF;
END $$;

INSERT INTO category_map (market_id, market_category, category_id)
SELECT m.id, r.market_category, c.id
FROM rules r
JOIN markets m ON m.name = r.market
JOIN categories c ON c.slug = r.slug;

COMMIT;

-- Market categories no rule covers yet; their products appear in no category.
-- Run it after a scrape to see what a market added:
--
--   SELECT m.name, p.category, count(*)
--   FROM products p
--   JOIN markets m ON m.id = p.market_id
--   LEFT JOIN category_resolution r ON r.market_id = p.market_id AND r.category = p.category
--   WHERE r.category_id IS NULL
--   GROUP BY 1, 2 ORDER BY 1, 2;
